version: "3.9"

services:
  backend:
    build:
      context: ./expense_splitwise
      dockerfile: Dockerfile
    container_name: django_backend
    volumes:
      - ./expense_splitwise:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: react_frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: expense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: