# Generated by Django 5.2.1 on 2025-05-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
