name: CI/CD Deploy Fullstack App (Prep Only)

on:
  push:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log build context (for debug)
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Repo: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          ls -la